name: learn-github-actions-test
on: [push]
jobs:
  bdd-tests:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1      
      - run: |
          cd ui
          npm install
          npm run build
          npm start &
          cd ../bdd
          npm install
          curl -v http://localhost:5000
          curl -v http://localhost:5000/build/bundle.js
          npm run test-ci
        env:
          CI: true

      - run: curl -v http://testhost:5000
      - run: curl -v http://testhost:5000/build/bundle.js
