name: learn-github-actions-test
on: [push]
jobs:
  bdd-tests:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    container:
      image: node
      options: --network-alias testhost
    defaults:
      run:
        working-directory: bdd
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      
      - name: Run UI in background
        working-directory: ui
        run: |
          npm install
          npm run build
          npm start &
        env:
          CI: true
          HOST: testhost

      - run: npx wait-port -t 10000 testhost:5000
   
      - run: npm install
#       - run: curl -v http://testhost:5000
      - run: curl -v http://testhost:5000/build/bundle.js
      - run: npm run test-ci
        env:
          CI: true
          SELENIUM_URL: http://selenium:4444/wd/hub/
