name: learn-github-actions-test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bdd
    services:
      selenium:
        image: selenium/standalone-chrome
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run test-ci
        env:
          CI: true
          SELENIUM_URL: http://selenium:4444/wd/hub/
