name: learn-github-actions-test
on: [push]
jobs:
  bdd-tests:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: nanasess/setup-chromedriver@master
      - run: |
          set -euo pipefail
          whereis google-chrome
          google-chrome -version
          google-chrome --headless --enable-logging=stderr --v=1
          ps aux
          cd ui
          npm install
          npm run build
          npm start &
          cd ../bdd
          npm install
          curl -v http://localhost:5000
          curl -v http://localhost:5000/build/bundle.js
          npm run test-ci
        env:
          CI: true

      - run: curl -v http://testhost:5000
      - run: curl -v http://testhost:5000/build/bundle.js
