name: learn-github-actions-test
on: [push]
jobs:
  bdd-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          cd ui
          npm install
          npm run build
          npm start &
          cd ../bdd
          npm install
          npx wait-port -t 10000 localhost:5000
          npm run test-ci
        env:
          CI: true
