name: bdd-tests
on: [push]
jobs:
  bdd-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - uses: actions/setup-node@v1
      - name: Start UI and tests
        run: |
          cd ui
          npm install
          npm run dev &
          cd ../bdd
          npm install
          npx wait-port -t 10000 localhost:9000
          npm run test-ci
        env:
          CI: true
          HEADLESS_CHROME: true